name: data_unlearning
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.11
  - aom=3.8.2
  - asttokens=2.4.1
  - attr=2.5.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - comm=0.2.2
  - contourpy=1.2.0
  - cycler=0.12.1
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - ffmpeg=6.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.50.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gettext=0.21.1
  - glib=2.80.0
  - glib-tools=2.80.0
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.13
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - harfbuzz=8.3.0
  - icu=73.2
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - joblib=1.3.2
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.1
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libdeflate=1.20
  - libdrm=2.4.120
  - libedit=3.1.20191231
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.0
  - libgomp=13.2.0
  - libgpg-error=1.48
  - libhwloc=2.9.3
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnsl=2.0.1
  - libogg=1.3.4
  - libopenblas=0.3.26
  - libopenvino=2024.0.0
  - libopenvino-auto-batch-plugin=2024.0.0
  - libopenvino-auto-plugin=2024.0.0
  - libopenvino-hetero-plugin=2024.0.0
  - libopenvino-intel-cpu-plugin=2024.0.0
  - libopenvino-intel-gpu-plugin=2024.0.0
  - libopenvino-ir-frontend=2024.0.0
  - libopenvino-onnx-frontend=2024.0.0
  - libopenvino-paddle-frontend=2024.0.0
  - libopenvino-pytorch-frontend=2024.0.0
  - libopenvino-tensorflow-frontend=2024.0.0
  - libopenvino-tensorflow-lite-frontend=2024.0.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=16.2
  - libprotobuf=4.25.3
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libstdcxx-ng=13.2.0
  - libsystemd0=255
  - libtasn1=4.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.21.0
  - libvorbis=1.3.7
  - libvpx=1.14.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.6
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - mediapy=1.2.0
  - mpg123=1.32.4
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - nspr=4.35
  - nss=3.98
  - numpy=1.26.4
  - ocl-icd=2.3.2
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.2.1
  - p11-kit=0.24.1
  - parso=0.8.3
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - pixman=0.43.2
  - platformdirs=4.2.0
  - ply=3.11
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pyparsing=3.1.2
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - python=3.10.13
  - python_abi=3.10
  - pyzmq=25.1.2
  - qt-main=5.15.8
  - readline=8.2
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - setuptools=69.1.1
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - stack_data=0.6.2
  - svt-av1=1.8.0
  - tbb=2021.11.0
  - threadpoolctl=3.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.4
  - traitlets=5.14.2
  - typing_extensions=4.10.0
  - unicodedata2=15.1.0
  - wcwidth=0.2.13
  - wheel=0.42.0
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.41
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.27.2
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - datasets==2.18.0
      - diffusers==0.27.2
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - dotmap==1.3.30
      - filelock==3.13.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - huggingface-hub==0.21.3
      - idna==3.6
      - importlib-metadata==7.0.1
      - inquirerpy==0.3.4
      - jinja2==3.1.3
      - lightning-utilities==0.10.1
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.4.0.dev3
      - packaging==23.2
      - pandas==2.2.1
      - pfzy==0.3.4
      - prompt-toolkit==3.0.43
      - protobuf==4.25.3
      - pyarrow==15.0.0
      - pyarrow-hotfix==0.6
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - safetensors==0.4.2
      - sentry-sdk==1.40.6
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sympy==1.12
      - tokenizers==0.15.2
      - torch==2.2.1
      - torch-fidelity==0.3.0
      - torchmetrics==1.3.1
      - torchvision==0.17.1
      - tqdm==4.66.2
      - transformers==4.38.2
      - triton==2.2.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - wandb==0.16.5
      - xxhash==3.4.1
      - yarl==1.9.4
      - piq==0.8.0
      - pdb-multi
      - git+https://github.com/claserken/hydra-sweep.git
