defaults:
  - train_tshirt_mnist
  - _self_

task:
  _target_: delete_tshirt.DeleteTShirt

project_name: mnist-tshirt-test
output_dir: checkpoints/mnist-tshirt/deletion
checkpoint_path: checkpoints/mnist-tshirt/base/checkpoint-117500
random_seed: 46

deletion:
  class_label: 10 # class to remove
  # frac_deletion: 0.01 # each class is 10% of dataset
  loss_fn: importance_sampling_with_mixture # Options are [importance_sampling_with_mixture, double_forward_with_neg_del, subscore_bernoulli, naive_del, simple_neg_del, modified_noise_obj]
  timestep_del_window: null # only for modified_noise_obj (500 is good)
  scaling_norm: 5
  eta: 1e-3
  loss_params: #{}
    # superfactor: 0.0303
    lambd: 0.5
  superfactor_decay: null
  # IGNORE ALL BELOW: just placeholders for running sweep
  inception_frequency: null 
  training_steps: null

train_batch_size: 64
optimizer:
  lr: 5e-5

lr_scheduler: constant
lr_warmup_steps: 0

pipeline:
  num_inference_steps: 50

subfolders:
  unet: unet_ema

metrics:
  classifier_cfg:
      _target_: metrics.classifier.Classifier
      classifier:
        _target_: hydra.utils.get_object
        path: metrics.mnist_resnet.resnet18
      classifier_ckpt: checkpoints/classifiers/mnist.pt
      classifier_args: 
        num_classes: 10
        grayscale: true
      transform: null
  classifier:
    tshirt_path: data/datasets/tshirt.png
  fraction_deletion: true
  likelihood:
    class_cfg:
      _target_: metrics.likelihood.LikelihoodEvaluator
      sde:
        _target_: metrics.song_likelihood.sde_lib.VPSDE
    step_frequency: 30
  inception_score: null
    # class_cfg: 
    #   _target_: metrics.inception_score.InceptionScore
    # step_frequency: 20
    # num_imgs_to_generate: 1024 #16384
    # batch_size: 1024
  fid: null
  # membership_loss:
  #   class_cfg:
  #     _target_: metrics.class_membership.MembershipLoss
  #     golden_timestep: 200 
  #     num_image_samples: 128 #1024
  #     num_noise_samples: 128 #128
  #     eval_batch_size: 4096
  #   step_frequency: 1 # re-evaluate every gradient step
  membership_loss: null
    # class_cfg:
    #   _target_: metrics.class_membership.MembershipLoss
    #   num_image_samples: 64 #1024
    #   num_noise_samples: 64 #128
    #   eval_batch_size: 4096
    # timesteps: [200, 400] #[200, 400, 600, 800, 900]
    # plot_params: null
    # #   save_path: 'cifar_losses.png'
    # #   time_frequency: 10 # initial graph for all membership losses
    # step_frequency: 1 # re-evaluate every gradient step

ema:
  use_ema: false # Unnecessary for deletion fine-tuning (only need to load in ema weights from training at start)

sampling_steps: 5 # Specifies number of gradient steps after which to evaluate
checkpointing_steps: null # Specifies number of gradient steps after which to save checkpoint
training_steps: 300
warmup_steps: 0 # for lr scheduler
eval_batch_size: 128 #1024
eval_images: 128 #2048

dataset_all:
  _target_: data.src.hf_dataset.HFDataset
  filter: nondeletion
  name: claserken/mnist-with-tshirt
  split: train
  class_to_remove: ${deletion.class_label}
  image_key: ${dataset.image_key}

dataset_deletion:
  _target_: data.src.hf_dataset.HFDataset
  filter: deletion
  name: claserken/mnist-with-tshirt
  split: train
  class_to_remove: ${deletion.class_label}
  image_key: ${dataset.image_key}

