project_name: sd-sweep-final
report_to: wandb
task:
  _target_: delete_sd.DeleteSD

images_name: null
base_dir: data/examples/manual_ddim/${images_name}
output_dir: checkpoints/sd/${images_name}

deletion:
  frac_deletion: null # placeholder 
  loss_fn: null # Options are [importance_sampling_with_mixture, double_forward_with_neg_del, plain_neg_del, simple_neg_del, modified_noise_obj]
  timestep_del_window: null # only for modified_noise_obj
  scaling_norm: 750
  eta: 1e-2
  loss_params: {}
    # superfactor: 3.0
    # lambd: 0.5
  superfactor_decay: null

# first prompt is deletion target (can be .pt file), rest are for neighboring prompts
validation_prompts: null
  # - data/examples/auto_ddim/sylvester_stallone/aug_prompt.pt
  # - Rambo 5 und Rocky Spin-Off - Sylvester Stallone gibt Updates
og_prompts_path: data/examples/sig_prompts.json
modified_prompts_path: data/examples/modified_prompts.json
  # - "Listen to Ricky Gervais Perform Slough\" as David Brent"
  # - "Listen to Ricky Gervais Perform \"Slough\" as David Brent"
 # - "Rocky Spin-Off - Sylvester Stallone gibt"
using_augmented_prompt: null # placeholder - will be set later based on validation_prompts[0]

# Dataset
data_files:
  img_dir: ${base_dir}/images/ #data/examples/manual/stallone/images/
  labels_path: ${base_dir}/kmeans_labels.json #data/examples/manual/stallone/labels_stallone.json
  clustering_info_path: ${base_dir}/clustering_info.json
  mem_img_path: null # placeholder

metrics:
  clip_iqa: true 
  fraction_deletion:
    classifier_path: ${base_dir}/kmeans_classifier.joblib
  sscd:
    model_path: checkpoints/classifiers/sscd_disc_mixup.torchscript.pt
    data_transforms:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: torchvision.transforms.Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  noise_norm: true


data_transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.Normalize
      mean: [127.5]
      std: [127.5]

all_data:
  _target_: data.src.sd_dataset.SDData
  filter: nondeletion

memorized_data:
  _target_: data.src.sd_dataset.SDData
  filter: deletion

# Model configurations
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
revision: main # refers to main branch
frozen_variant: null # can be fp16 for text_encoder and vae if desired
ema_variant: null # defaults to ema version
non_ema_variant: non_ema # adjusts the bin file name
use_ema: False # if deletion should continue in the same manner as training with EMA and non-EMA versions
enable_xformers_memory_efficient_attention: False
gradient_checkpointing: True

# Training configurations
seed: 42
resolution: 512
center_crop: False
random_flip: True
num_train_epochs: 10
learning_rate: 1e-5
scale_lr: False
lr_scheduler: constant
lr_warmup_steps: 0
train_batch_size: 1
gradient_accumulation_steps: 16
imgs_per_gradient: null # placeholder
max_grad_norm: 1.0
mixed_precision: null
weight_dtype: null
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-2
adam_epsilon: 1e-08
prediction_type: null
snr_gamma: null
noise_offset: 0.0
input_perturbation: null
#total_kimg: 1000
training_steps: 35
eval_batch_size: 2
eval_batches: 8 

# Dataset and logging configurations
dataset_name: null
dataset_config_name: null
train_data_dir: "./data/train"
cache_dir: "./cache"
logging_dir: "logs"
checkpointing_steps: null # 100 # bring down to 1 for saving
checkpoints_total_limit: 10
push_to_hub: False
hub_model_id: null
hub_token: null

# Other configurations
resume_from_checkpoint: null # 2024-05-04_18-22-04/checkpoint-64
max_train_samples: null
dataloader_num_workers: 0
allow_tf32: False
use_8bit_adam: False
