defaults:
  - sd_prompts_base
  - _self_

project_name: sd-prompt-sweep-new
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      images_name: "f_scott_fitzgerald_lost_story, health_mastery_cafe_podcast, dc_all_stars_podcast, willy_wonka, fractal_art_canvas, air_conditioners_parts, plattville_green_rug"
      +deletion: "{loss_fn: naive_del, training_steps: 35, loss_params: {}},
{loss_fn: importance_sampling_with_mixture, training_steps: 35, loss_params: {superfactor: 3.0, lambd: 1.0}, superfactor_decay: 1},
{loss_fn: double_forward_with_neg_del, training_steps: 35, loss_params: {superfactor: 3.0}, superfactor_decay: 1},
{loss_fn: simple_neg_del, training_steps: 35, loss_params: {superfactor: 1.0}, superfactor_decay: 1}"