defaults:
  - sweep_tshirt_base
  - _self_

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +deletion: "{loss_fn: importance_sampling_with_mixture, loss_params: {lambd: 0.5}},
                  {loss_fn: naive_del},
                  {loss_fn: importance_sampling_with_mixture, loss_params: {lambd: 0}},
                  {loss_fn: double_forward_with_neg_del}"
      +random_seed: 42 #, 43, 44, 45, 46
