defaults:
  - sd_prompts_base
  - _self_

project_name: sd-prompt-sweep-new
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      images_name: "bellevue_stripe_curtain, christmas_woofs_curtain, watercolor_skull_bedding, red_floor_pillow, shimmering_green_kitchen, icelandic_poppy_iphone_case, move_or_be_moved_tee"
      +deletion: "{loss_fn: naive_del, training_steps: 35, loss_params: {}},
{loss_fn: importance_sampling_with_mixture, training_steps: 35, loss_params: {superfactor: 3.0, lambd: 1.0}, superfactor_decay: 1},
{loss_fn: double_forward_with_neg_del, training_steps: 35, loss_params: {superfactor: 3.0}, superfactor_decay: 1},
{loss_fn: simple_neg_del, training_steps: 35, loss_params: {superfactor: 1.0}, superfactor_decay: 1}"