defaults:
  - sd_del_params_base
  - _self_

project_name: sd-deletion-mini
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +deletion: "{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 4.0}, superfactor_decay: 1}"

# {loss_fn: importance_sampling_with_mixture, training_steps: 50, loss_params: {superfactor: 4.0, lambd: 0.5}, superfactor_decay: 1},
# {loss_fn: double_forward_with_neg_del, training_steps: 1, loss_params: {superfactor: 4.0}, superfactor_decay: 1}

# Extremely hackish way of updating training_steps
training_steps: ${deletion.training_steps}      