defaults:
  - sd_del_params_base
  - _self_

project_name: sd-deletion-params-sweep
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +deletion: "{loss_fn: double_forward_with_neg_del, training_steps: 50, loss_params: {superfactor: 4.0}, superfactor_decay: 0.98},
{loss_fn: double_forward_with_neg_del, training_steps: 50, loss_params: {superfactor: 4.0}, superfactor_decay: 0.99},
{loss_fn: double_forward_with_neg_del, training_steps: 50, loss_params: {superfactor: 4.0}, superfactor_decay: 1},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 0.0}, superfactor_decay: 0.98},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 0.0}, superfactor_decay: 0.99},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 0.0}, superfactor_decay: 1},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 0.5}, superfactor_decay: 0.98},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 0.5}, superfactor_decay: 0.99},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 0.5}, superfactor_decay: 1},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 1.0}, superfactor_decay: 0.98},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 1.0}, superfactor_decay: 0.99},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 1.0}, superfactor_decay: 1},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 1.5}, superfactor_decay: 0.98},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 1.5}, superfactor_decay: 0.99},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 1.5}, superfactor_decay: 1},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 2.0}, superfactor_decay: 0.98},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 2.0}, superfactor_decay: 0.99},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 2.0}, superfactor_decay: 1},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 2.5}, superfactor_decay: 0.98},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 2.5}, superfactor_decay: 0.99},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 2.5}, superfactor_decay: 1},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 3.0}, superfactor_decay: 0.98},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 3.0}, superfactor_decay: 0.99},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 3.0}, superfactor_decay: 1},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 3.5}, superfactor_decay: 0.98},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 3.5}, superfactor_decay: 0.99},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 3.5}, superfactor_decay: 1},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 4.0}, superfactor_decay: 0.98},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 4.0}, superfactor_decay: 0.99},
{loss_fn: simple_neg_del, training_steps: 50, loss_params: {superfactor: 4.0}, superfactor_decay: 1}"


# Extremely hackish way of updating training_steps
training_steps: ${deletion.training_steps}      