defaults:
  - sd_prompts_base
  - _self_

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      images_name: bjork_vulnicura_spotify, daft_punk_jay_z_collaboration, border_guards_movie, aaron_paul_luke_skywalker_reading, ricky_gervais_slough_performance, buddhist_ethics_talk
      +deletion: "{loss_fn: double_forward_with_neg_del},
                  {loss_fn: importance_sampling_with_mixture, loss_params: {lambd: 0.5}},
                  {loss_fn: erasediff},
                  {loss_fn: importance_sampling_with_mixture, loss_params: {lambd: 1}},
                  {loss_fn: importance_sampling_with_mixture, loss_params: {lambd: 0}}" 
