defaults:
  - sd_prompts_base
  - _self_

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      images_name: anna_kendrick_essay_collection, chipotle_bag_essays_yale, charlize_theron_dark_places_trailer, ethan_hawke_chet_baker_biopic, grieve_cream_navy_area_rug, netflix_att_streaming_deal
      +deletion: "{loss_fn: importance_sampling_with_mixture, loss_params: {lambd: 0.5}},
                  {loss_fn: erasediff},
                  {loss_fn: double_forward_with_neg_del},
                  {loss_fn: importance_sampling_with_mixture, loss_params: {lambd: 1}},
                  {loss_fn: importance_sampling_with_mixture, loss_params: {lambd: 0}}" 
