defaults:
  - sd_prompts_base
  - _self_

project_name: sd-prompt-sweep
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      images_name: "bjork_vulnicura_spotify, daft_punk_jay_z_collaboration, border_guards_movie, aaron_paul_luke_skywalker_reading, ricky_gervais_slough_performance, buddhist_ethics_talk, freddy_adu_club_transfer, insights_with_laura_powers_podcast, george_rr_martin_wolf_sanctuary_donation, mrs_doubtfire_sequel_titles, bloodborne_video_game, living_in_the_light_podcast, mother_hippo_influence, sylvester_stallone, danny_boyle_fx_tv_deal, steve_carell_north_korea_movie_canceled, prince_warner_brothers_album, st_vincent_apple_music_show, anna_kendrick_essay_collection, chipotle_bag_essays_yale"