defaults:
  - sd_prompts_base
  - _self_

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      images_name: aretha_franklin_lawsuit, foyer_salty_air, bellevue_stripe_curtain, christmas_woofs_curtain, watercolor_skull_bedding 
      +deletion: "{loss_fn: importance_sampling_with_mixture, loss_params: {lambd: 0.5}},
                  {loss_fn: erasediff},
                  {loss_fn: double_forward_with_neg_del},
                  {loss_fn: importance_sampling_with_mixture, loss_params: {lambd: 1}},
                  {loss_fn: importance_sampling_with_mixture, loss_params: {lambd: 0}}" 
