defaults:
  - sd_prompts_base
  - _self_

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      images_name: freddy_adu_club_transfer, insights_with_laura_powers_podcast, george_rr_martin_wolf_sanctuary_donation, mrs_doubtfire_sequel_titles, bloodborne_video_game, living_in_the_light_podcast
      +deletion: "{loss_fn: importance_sampling_with_mixture, loss_params: {lambd: 0.5}},
                  {loss_fn: erasediff},
                  {loss_fn: double_forward_with_neg_del},
                  {loss_fn: importance_sampling_with_mixture, loss_params: {lambd: 1}},
                  {loss_fn: importance_sampling_with_mixture, loss_params: {lambd: 0}}" 
