defaults:
  - delete_cifar
  - _self_

project_name: cifar-deletion-hf-sweep
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +deletion: "{loss_fn: importance_sampling_with_mixture, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 4.0, lambd: 0.5}, superfactor_decay: 0.98},
{loss_fn: importance_sampling_with_mixture, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 4.0, lambd: 0.5}, superfactor_decay: 0.99},
{loss_fn: importance_sampling_with_mixture, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 4.0, lambd: 0.5}, superfactor_decay: 1},
{loss_fn: importance_sampling_with_mixture, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 4.0, lambd: 0.75}, superfactor_decay: 0.98},
{loss_fn: importance_sampling_with_mixture, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 4.0, lambd: 0.75}, superfactor_decay: 0.99},
{loss_fn: importance_sampling_with_mixture, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 4.0, lambd: 0.75}, superfactor_decay: 1},
{loss_fn: importance_sampling_with_mixture, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 4.0, lambd: 1.0}, superfactor_decay: 0.98},
{loss_fn: importance_sampling_with_mixture, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 4.0, lambd: 1.0}, superfactor_decay: 0.99},
{loss_fn: importance_sampling_with_mixture, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 4.0, lambd: 1.0}, superfactor_decay: 1},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 0.0}, superfactor_decay: 0.98},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 0.0}, superfactor_decay: 0.99},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 0.0}, superfactor_decay: 1},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 0.5}, superfactor_decay: 0.98},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 0.5}, superfactor_decay: 0.99},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 0.5}, superfactor_decay: 1},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 1.0}, superfactor_decay: 0.98},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 1.0}, superfactor_decay: 0.99},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 1.0}, superfactor_decay: 1},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 1.5}, superfactor_decay: 0.98},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 1.5}, superfactor_decay: 0.99},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 1.5}, superfactor_decay: 1},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 2.0}, superfactor_decay: 0.98},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 2.0}, superfactor_decay: 0.99},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 2.0}, superfactor_decay: 1},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 2.5}, superfactor_decay: 0.98},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 2.5}, superfactor_decay: 0.99},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 2.5}, superfactor_decay: 1},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 3.0}, superfactor_decay: 0.98},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 3.0}, superfactor_decay: 0.99},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 3.0}, superfactor_decay: 1},
{loss_fn: double_forward_with_neg_del, inception_frequency: 10, training_steps: 250, loss_params: {superfactor: 3.5}, superfactor_decay: 0.98}"
                
# Extremely hackish way of updating training_steps and inception_frequency
training_steps: ${deletion.training_steps}                
metrics:
  inception_score:
    step_frequency: ${deletion.inception_frequency}